name: Test Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: 'Asia/Seoul'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Scheduled test is running"
          date